### ISSUE TITLE
Inconsistent definition of "switch-type" LOCK_OUT

### ISSUE THREAD

**Issue by michbin** [openBackhaul/synchronization#26]
The definition of the values for the `switch-type` attribute in the `sync-protection-spec` grouping is not clear:

* `SWITCH_TYPE_LOCK_OUT` applies to a sync source but not to the source selection process itself.

**Comment by openBackhaul** [comment]
**Status of discussion on DMIP call on 21st of July 2022:**
Potentially the "LOCK_OUT" value needs to be removed from the SwitchType enumeration and an additional isTemporarilyExcludedFromSourceSwitching : boolean attribute would be added to the SyncLpSpec (?) or a new class that is augment it.

**Comment by demx8as6** [comment]
Proposal to the 5G-xhaul call on 21th of September 2022:
Assuming that [issue #45](https://github.com/openBackhaul/synchronization/issues/45) will be approved, then this issue is obsolete, because the "switch-type" attributed was removed. Issue should be closed without further explanations.
