### ISSUE TITLE
description change on parameter 

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/synchronization#46]
The issue is related to https://github.com/openBackhaul/synchronization/issues/27

The current description should be changed **from** ...

" ... . Frames with 01-80-C2-00-00-0E get dropped at intermediate switches. Frames with 01-1B-19-00-00-00 get forwarded."

... **to** ...

" ... . Frames with 01-80-C2-00-00-0E **_may_** get dropped at intermediate switches. Frames with 01-1B-19-00-00-00 get forwarded."

The reason is that there are Frames could be destined to other devices but don't got to the clock of THIS device.

**Comment by openBackhaul** [comment]
Have decide to document the requested change in the already existing issue #27 .
