### ISSUE TITLE
Attribute wtr in SyncProtectionSpec is missing

### ISSUE THREAD

**Issue by Tsyncsupport** [openBackhaul/synchronization#5]
The attribute "wtr" in SyncProtectionSpec is missing

Attribute name:
wtr

Type:
Integer RW

Description:
Wait to restore time. A previously failed synchronization source is only again considered as available by the selection process if it is fault-free for wtr time.

**Comment by openBackhaul** [comment]
There is a ControlParameters_Pac::waitToRevertTime attribute that does the job.
See decision in issue #25.
