### ISSUE TITLE
To resolve the warning caused by using the non configurable attribute "external-clock-port" in the "when statement"

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/synchronization#56]
Parent issue : https://github.com/openBackhaul/synchronization/issues/54

Augmenting the SsmExternalClock_Pac,SsmInBand_Pac to SyncLpSpec will augment this pacs to the layerProtocol

```
augment "/core-model:control-construct/core-model:logical-termination-point/core-model:layer-protocol" {
when "./synchronization:external-clock-port = ’true’”;
uses ssm-external-clock-pac;
description
"none";
}
 
augment "/core-model:control-construct/core-model:logical-termination-point/core-model:layer-protocol" {
when "./synchronization:external-clock-port = ’false’”;
uses ssm-in-band-pac;
description
"none";
}
```

Since the attribute in the when statement is readonly , the following warning is observed in the pyang output, 
1. synchronization-1-0.yang:110: warning: node "synchronization-1-0::external-clock-port" is config false and is not part of the accessible tree
2. synchronization-1-0.yang:117: warning: node "synchronization-1-0::external-clock-port" is config false and is not part of the accessible tree

**Proposal :** Using a if-feature statement instead of a when statement will solve this warning.( If interested , this approach shall be discussed further)

**Comment by michbin** [comment]
A Yang `feature` (and thus an `if-feature` statement) **cannot** be used because both containers (`ssm-external-clock-pac`, `ssm-in-band-pac`) can be present in a device.
(The first container is used for external clock ports, the second is applied to traffic ports used as sync ports.)

**Comment by openBackhaul** [comment]
This issue is covered by the proposal/decision formulated in issue #54
